# Generated by Django 3.2.16 on 2023-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='image_url',
            field=models.TextField(default=None, null=True),
        ),
    ]
