# Generated by Django 3.2.16 on 2023-12-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='variatid',
            new_name='variantid',
        ),
    ]
