# Generated by Django 3.2.16 on 2023-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='additional_note',
            field=models.TextField(default=None, null=True),
        ),
    ]
