# Generated by Django 3.2.16 on 2023-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20230313_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='has_url',
            field=models.BooleanField(default=False),
        ),
    ]
