# Generated by Django 3.2.16 on 2023-06-02 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_digitalproduct_has_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='has_serial_keys',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='productSKU',
        ),
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
