# Generated by Django 3.2.16 on 2023-06-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_file_additional_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderkeys',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderkeys',
            name='serial_key',
        ),
        migrations.RemoveField(
            model_name='variantfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='variantfile',
            name='variant',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='last_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product',
            new_name='digital_product',
        ),
        migrations.RemoveField(
            model_name='serialkey',
            name='file',
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serialkey',
            name='digital_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.digitalproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='shopify_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderKeys',
        ),
        migrations.DeleteModel(
            name='VariantFile',
        ),
        migrations.AddField(
            model_name='digitalproductfile',
            name='digital_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.digitalproduct'),
        ),
        migrations.AddField(
            model_name='digitalproductfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.file'),
        ),
    ]
